POST http://localhost:3332/itens
Content-type: application/json

{
 "title": "item 2",
 "teste": "nova descrição"   
}

###

GET http://localhost:3332/itens
###

PUT http://localhost:3332/itens/b423f321-451a-41c6-a90c-82b84ee7f48d
Content-type: application/json

{
 "title": "item atualizado",
 "teste": "teste de atualização"   
}

### 

DELETE http://localhost:3332/itens/fde9ca00-6ecd-40ee-bae1-ef1544b818a7
